[package]
name = "syng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
ciborium = "0.2.0"
serde = { version = "1.0.158", features = ["derive"] }
sha256 = "1.1.2"
