[package]
name = "syng-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syng = { path = "../syng-core/" }
ciborium = "0.2.0"